### ISSUE TITLE
mac上需要指定默认字体?

### ISSUE THREAD

**Issue by gsxgmpkt9020** [john-guo/MEBatch#1]
`Traceback (most recent call last):
  File "mebatch.py", line 161, in <module>
    main()
  File "mebatch.py", line 147, in main
    FONT = ImageFont.truetype(opts.font, opts.fontsize)
  File "/Users/zhangyang/anaconda2/lib/python2.7/site-packages/PIL/ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Users/zhangyang/anaconda2/lib/python2.7/site-packages/PIL/ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
IOError: cannot open resource`

**Comment by john-guo** [comment]
默认使用了windows的simhei.ttf字体，命令行还有些参数没写在readme里，可以用 --font 字体文件 指定字体
